name: Explorando-GitHub-Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  explorar:
    runs-on: ubuntu-latest
   
    steps:
      - name: Paso 1 - Verificar c칩digo
        run: echo "Verificando el c칩digo del repositorio"
       
      - name: Paso 2 - Mostrar mensaje
        run: echo "Este es un flujo de trabajo b치sico de GitHub Actions"
       
      - name: Paso 3 - Mostrar variables
        run: |
          echo "Ejecut치ndose en runner: $RUNNER_OS"
          echo "Directorio de trabajo: $GITHUB_WORKSPACE"
